CONSOLE_LOG_LEVEL: INFO
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@localhost:5672/
DB_CONNECTION: sqlite:///../../../Outputs/database/db.sql
DB_DIR: ../../../Outputs/database
AIHIVE_ADDR: https://api.aihive.ir  # webhook base address
BASE_URL_FILE_LINK: http://localhost:8009  # current service base address